language: generic
services:
    - docker

before_install: 
    - docker build -t krc04/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true krc04/react-test npm test -- --coverage

after_success:
    - docker build -t krc04/multi-client ./client
    - docker build -t krc04/multi-nginx ./nginx
    - docker build -t krc04/multi-server ./server
    - docker build -t krc04/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take these images and push to docker hub
    - docker push krc04/multi-client
    - docker push krc04/multi-nginx
    - docker push krc04/multi-server
    - docker push krc04/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-630411679375"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY